from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class BotRecord:
    """Database-agnostic representation of a bot row returned to callers.

    Attributes:
        id: UUID primary key.
        name: Display name shown in the UI.
        description: Short description of the bot's purpose.
        type: Bot-type slug (e.g. ``"communicator"``).
        provider: LLM backend identifier — one of ``"ollama"``, ``"anthropic"``,
            or ``"openai"``.  Determines which provider adapter the chat route uses.
        model: Provider-specific model identifier (e.g. ``"qwen2.5:7b"`` for Ollama
            or ``"claude-sonnet-5"`` for Anthropic).  Empty string means the
            provider adapter uses its own default.
        system_prompt: Custom instructions injected before each conversation.
        icon: Emoji used to represent this bot in the UI.
        active: Whether the bot is visible to non-admin users.
        restricted: Minimum role required to use this bot (``"user"`` or ``"admin"``).
        modules: IDs of the modules this bot is scoped to.
        created_by: Email of the admin who created this bot.
        created_at: Server-side creation timestamp.
    """

    id: str                           # UUID primary key; generated by the DB on insert
    name: str                         # display name rendered in bot lists and log entries
    description: str                  # short description shown in the bot picker and admin UI
    type: str                         # bot-type slug matched against bot_types.name at runtime
    provider: str                     # LLM backend: "ollama", "anthropic", or "openai"
    model: str                        # provider-specific model string; empty defers to adapter default
    system_prompt: str                # instructions prepended to every conversation context
    icon: str                         # emoji identifier displayed next to the bot name
    active: bool                      # True when the bot should be visible to non-admin users
    restricted: str                   # "user" or "admin"; controls who can start a conversation
    modules: list[str]                # list of module IDs this bot is associated with
    created_by: str                   # email of the admin who provisioned this bot
    config_schema: dict = field(default_factory=dict)  # declarative UI schema for the bot config page; empty dict if unused
    created_at: datetime | None = None  # server-set creation timestamp; None before the first DB read
