apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: spin-core-secrets
    envs:
      - .env
    options:
      disableNameSuffixHash: true

resources:
  - namespace.yaml
  - configmap.yaml
  - app-data-pvc.yaml
  - postgres/pvc.yaml
  - postgres/service.yaml
  - postgres/statefulset.yaml
  - mongo/pvc.yaml
  - mongo/service.yaml
  - mongo/statefulset.yaml
  - clickhouse/pvc.yaml
  - clickhouse/service.yaml
  - clickhouse/statefulset.yaml
  - ollama/pvc.yaml
  - ollama/service.yaml
  - ollama/deployment.yaml
  - ollama/model-downloader-job.yaml
  - backend/service.yaml
  - backend/deployment.yaml
  - chatbot/service.yaml
  - chatbot/deployment.yaml
  - hello-world/service.yaml
  - hello-world/deployment.yaml
  - frontend/service.yaml
  - frontend/deployment.yaml
