apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anomascan-yolo-pvc  # persistent storage for YOLO weight files across pod restarts
  namespace: spin-core
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
